// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
  
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("HawKeys")]
[assembly: AssemblyDescription("Easily insert unicode ʻokina and kahakō characters used in Hawaiian.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Jon Thysell")]
[assembly: AssemblyProduct("HawKeys")]
[assembly: AssemblyCopyright("Copyright © Jon Thysell 2019")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

[assembly: AssemblyVersion("1.2.1.0")]
[assembly: AssemblyFileVersion("1.2.1.0")]

[assembly: NeutralResourcesLanguage("en")]